version: '3'

services:
  nifi:
    image: apache/nifi
    container_name: nifi
    environment:
      - NIFI_WEB_HTTP_PORT=8080
    ports:
      - 8080:8080
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - ./data:/home/u/data
      - ./nifi/logs:/opt/nifi/nifi-current/logs
      # - ./nifi/conf:/opt/nifi/nifi-current/conf
      # - ./nifi/state:/opt/nifi/nifi-current/state
      # - ./nifi/db:/opt/nifi/nifi-current/database_repository
      # - ./nifi/flowfile:/opt/nifi/nifi-current/flowfile_repository
      # - ./nifi/content:/opt/nifi/nifi-current/content_repository
      # - ./nifi/provenance:/opt/nifi/nifi-current/provenance_repository


# https://docs.cloudera.com/HDPDocuments/HDF1/HDF-1.1.1/bk_HDF_Upgrade/content/HDF_Upgrade.html